apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: application-springboot:latest
        ports:
        - name: http-port
          containerPort: 8080
        env:
          - name: api-application
            value: "http://application:8080/"
        imagePullPolicy: Always
